#!/usr/bin/env python3
import subprocess
try:
    status=subprocess.run(["git", "status", "--porcelain"], timeout=0.1, capture_output=True)
    if status.stdout:
        print("*")
except subprocess.TimeoutExpired as e:
    print("?")

