#!/usr/bin/env python3
import subprocess
import time
try:
    # Since `git status` is slow with large repositories, run the fast `git diff --shortstat` first, and then run `git status --porcelain` only if `git diff --shortstat` finishes in 70ms.
    t1=time.monotonic()
    if subprocess.run(["git", "diff", "--shortstat"], timeout=2, capture_output=True).stdout:
        print("*")
    else:
        t2=time.monotonic()
        if t2 - t1 < 0.07:
            if subprocess.run(["git", "status", "--porcelain"], timeout=10, capture_output=True).stdout:
                print("*")
        else:
            print("?")
except subprocess.TimeoutExpired as e:
    print("?")

